[package]
name = "dass-e2e"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
anyhow.workspace = true
async-trait.workspace = true
dass-engine = { path = "../dass-engine" }
petgraph.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
