[package]
name = "dass-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
crossterm.workspace = true
serde_json.workspace = true
ratatui.workspace = true
tokio = { workspace = true, features = ["full"] }
