[package]
name = "pulpo-tools"
version = "0.1.1"
edition = "2024"

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
rio_api = "0.8.5"
rio_turtle = "0.8.5"
serde.workspace = true
serde_json.workspace = true
pulpo-engine = { workspace = true }
console = "0.15"
petgraph.workspace = true
